/*
Copyright © 2026 Flare LAN Revival contributors

This file is part of FLARE.

FLARE is free software: you can redistribute it and/or modify it under the terms
of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version.

FLARE is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
FLARE.  If not, see http://www.gnu.org/licenses/
*/

#ifndef REPLAY_H
#define REPLAY_H

#include <stdint.h>
#include <fstream>
#include <string>
#include <vector>

/** Records per-tick input to a file, and plays it back.
 *
 * This is what makes the world digest mean anything. Without input nothing in the world moves --
 * enemies idle until a player approaches and the player never does -- so a digest taken over an
 * unattended server is sensitive to the starting conditions and blind to combat, movement,
 * pathfinding, powers and loot. Measured before this existed: a +50% change to movement speed,
 * over 3000 ticks, did not move the digest at all. See plans/phase0/P0.5a.
 *
 * The interception point is InputState's public state arrays, applied once per tick just before
 * the game logic runs. Avatar reads inpt-> in 35 separate places and this class deliberately
 * touches none of them; P1.1 restructures input properly.
 *
 * FORMAT is plain text, one line per tick, so a recording can be AUTHORED as well as captured.
 * That matters more than it sounds: recording by hand needs a client, a display and a person,
 * while an authored recording ("hold west for 400 ticks, then attack") can be generated by a
 * script and reviewed in a diff.
 *
 * A recording carries the engine version, the active mod list and the simulation seed. A
 * mismatch is REFUSED rather than replayed, because a replay that silently drifts from its
 * recording produces a confidently wrong answer, which is worse than no answer.
 */
class Replay {
public:
	static const int FORMAT_VERSION = 1;

	Replay();
	~Replay();

	bool startRecording(const std::string& path);

	/** Reads and validates the header. Returns false (and logs why) on any mismatch. */
	bool startPlayback(const std::string& path);

	bool isRecording() const { return recording; }
	bool isPlaying() const { return playing; }

	/** The seed the recording was made with. Only meaningful after startPlayback(). */
	uint64_t getSeed() const { return seed; }

	/** Number of input frames read from the file. Only meaningful after startPlayback(). */
	size_t frameCount() const { return frames.size(); }

	/** Capture this tick's input. */
	void recordTick(unsigned long tick);

	/** Drive InputState from the recording. Ticks past the end leave input released, so a
	 * replay can be run longer than its recording to watch the world settle. */
	void applyTick(unsigned long tick);

	void finish();

private:
	struct Frame {
		unsigned long tick;
		uint64_t pressing;
		uint64_t lock;
		int mouse_x;
		int mouse_y;
		Frame() : tick(0), pressing(0), lock(0), mouse_x(0), mouse_y(0) {}
	};

	static std::string currentModList();

	bool recording;
	bool playing;
	uint64_t seed;
	std::ofstream out;
	std::vector<Frame> frames;
	size_t next_frame;
};

extern Replay* replay;

#endif // REPLAY_H
