# Simulation sources -- must link with no SDL2_image, SDL2_mixer, or SDL2_ttf.
# See plans/phase1/P1.4a-map-owns-collision-and-signals.md and
# plans/phase1/P1.4b-flare-sim-source-partition.md for how this list was measured.
Set (FLARE_SIM_SOURCES
	./src/AStarContainer.cpp
	./src/AStarNode.cpp
	./src/ActionBarState.cpp
	./src/Avatar.cpp
	./src/CampaignManager.cpp
	./src/EffectManager.cpp
	./src/EnemyGroupManager.cpp
	./src/EngineSettings.cpp
	./src/Entity.cpp
	./src/EntityBehavior.cpp
	./src/EntityManager.cpp
	./src/EventManager.cpp
	./src/FileParser.cpp
	./src/FogOfWar.cpp
	./src/GetText.cpp
	./src/Hazard.cpp
	./src/HazardManager.cpp
	./src/ItemManager.cpp
	./src/ItemStorage.cpp
	./src/LabelInfo.cpp
	./src/Loot.cpp
	./src/LootManager.cpp
	./src/Map.cpp
	./src/MapCollision.cpp
	./src/MapSaver.cpp
	./src/MessageEngine.cpp
	./src/ModManager.cpp
	./src/net/NetPlatform.cpp
	./src/net/NetProtocol.cpp
	./src/net/NetworkManager.cpp
	./src/NPC.cpp
	./src/NPCManager.cpp
	./src/PlayerCommand.cpp
	./src/PlayerInventory.cpp
	./src/PlayerManager.cpp
	./src/PowerBonusState.cpp
	./src/PowerManager.cpp
	./src/Rng.cpp
	./src/Settings.cpp
	./src/SharedGameResources.cpp
	./src/SimEvents.cpp
	./src/StatBlock.cpp
	./src/Stats.cpp
	./src/TileSet.cpp
	./src/TooltipData.cpp
	./src/Utils.cpp
	./src/UtilsDebug.cpp
	./src/UtilsFileSystem.cpp
	./src/UtilsParsing.cpp
	./src/Version.cpp
	./src/WorldHash.cpp
	./src/XPScaling.cpp
)

# Presentation sources -- SDL rendering, audio, menus, and widgets.
Set (FLARE_PRESENTATION_SOURCES
	./src/Animation.cpp
	./src/AnimationManager.cpp
	./src/AnimationMedia.cpp
	./src/AnimationSet.cpp
	./src/Camera.cpp
	./src/net/ChildProcess.cpp
	./src/CombatText.cpp
	./src/CursorManager.cpp
	./src/DeviceList.cpp
	./src/FontDeviceList.cpp
	./src/FontEngine.cpp
	./src/GameSlotPreview.cpp
	./src/GameState.cpp
	./src/GameStateConfig.cpp
	./src/GameStateCutscene.cpp
	./src/GameStateLoad.cpp
	./src/GameStateNew.cpp
	./src/GameStatePlay.cpp
	./src/GameStateTitle.cpp
	./src/GameSwitcher.cpp
	./src/IconManager.cpp
	./src/InputState.cpp
	./src/MapParallax.cpp
	./src/MapRenderer.cpp
	./src/Menu.cpp
	./src/MenuActionBar.cpp
	./src/MenuActiveEffects.cpp
	./src/MenuBook.cpp
	./src/MenuCharacter.cpp
	./src/MenuConfig.cpp
	./src/MenuConfirm.cpp
	./src/MenuDevConsole.cpp
	./src/MenuEnemy.cpp
	./src/MenuExit.cpp
	./src/MenuGameOver.cpp
	./src/MenuHUDLog.cpp
	./src/MenuInventory.cpp
	./src/MenuItemStorage.cpp
	./src/MenuLog.cpp
	./src/MenuManager.cpp
	./src/MenuMiniMap.cpp
	./src/MenuNumPicker.cpp
	./src/MenuPowers.cpp
	./src/MenuRegionTitle.cpp
	./src/MenuStash.cpp
	./src/MenuStatBar.cpp
	./src/MenuTalker.cpp
	./src/MenuTouchControls.cpp
	./src/MenuVendor.cpp
	./src/NullFontEngine.cpp
	./src/NullInputState.cpp
	./src/NullRenderDevice.cpp
	./src/NullSoundManager.cpp
	./src/QuestLog.cpp
	./src/RenderDevice.cpp
	./src/Replay.cpp
	./src/ScriptedInputState.cpp
	./src/SDLFontEngine.cpp
	./src/SDLHardwareRenderDevice.cpp
	./src/SDLInputState.cpp
	./src/SDLSoftwareRenderDevice.cpp
	./src/SDLSoundManager.cpp
	./src/SaveLoad.cpp
	./src/SharedResources.cpp
	./src/SoundManager.cpp
	./src/Subtitles.cpp
	./src/TooltipManager.cpp
	./src/Widget.cpp
	./src/WidgetButton.cpp
	./src/WidgetCheckBox.cpp
	./src/WidgetHorizontalList.cpp
	./src/WidgetInput.cpp
	./src/WidgetLabel.cpp
	./src/WidgetListBox.cpp
	./src/WidgetLog.cpp
	./src/WidgetScrollBar.cpp
	./src/WidgetScrollBox.cpp
	./src/WidgetSlider.cpp
	./src/WidgetSlot.cpp
	./src/WidgetTabControl.cpp
	./src/WidgetTooltip.cpp
)
